### ISSUE TITLE
Kafka Ingester: Clarify config documentation and examples

### ISSUE THREAD

**Issue by ashnwade** [gravwell/wiki#1047]
# Documentation

## What needs to be documented?
I noticed one of the examples of a valid config is using the "default-tag", "Tags", and "tag-header" option in the config block.    The other example is using the standard "Tag-name" option.     Only the "tag-name" option however is explained within the documention.  

Thinking that either we need to clarify the information on the 3 key process for dynamic tags in the docs,  or remove it from the example.   

## Why is this documentation needed? 
Currently it's leading to some confusion on proper usage.

## Any other comments?
Came up due to a discussion in Discord

**Comment by ashnwade** [comment]
We should target this change to the earliest wiki release branch where this is applicable and then roll those changes up. If you do the initial change, I will do all the subsequent merging.

**Comment by john-floren-gravwell** [comment]
Specifically, `Tag-Name` is not valid, nor is `Key-As-Source` (another option documented in the wiki), and presumably other fields which have been changed over time. We need to walk the source code and make sure the wiki is only documenting what actually exists.
