### ISSUE TITLE
collectd documentation

### ISSUE THREAD

**Issue by traetox** [gravwell/wiki#148]
Add more about configuration, call out some of the changes you have to make to collectd configs to get usable data.

More example queries with more info about what/why we are doing things.

This is a low priority item, collectd is dead.  Long live prometheus and actual metrics.

**Comment by kris-watts-gravwell** [comment]
collectd is an absolutely atrocious system and i think the opentelemetry and prometheus folks won.  we will be going with those native metrics rather than collectd going forward.  I don't think we should add docs here.
