### ISSUE TITLE
left navigation menu can expand beyond the fold and has no scroll

### ISSUE THREAD

**Issue by remasis** [gravwell/wiki#229]
To see what I mean:
Load 1080p browser and hit https://docs.gravwell.io/#!ingesters/ingesters.md#The_Gravwell_Federator

The link for the Gravwell Federator section is below the fold but there is no way to scroll to see that content.

Suggestion: add scroll bar to nav.

**Comment by traetox** [comment]
I recommend that we break up this ingesters page.

The main page should have a list of the ingesters and a small blurb on what its for and why you would use it with a link to a page dedicated to the ingester.  The dedicated pages can have much more info with additional docs.

The current ingester megapage is hard to grok.

**Comment by traetox** [comment]
https://github.com/gravwell/wiki/pull/249
