### ISSUE TITLE
apt-key deprecation in Debian 11 and Ubuntu 22.04

### ISSUE THREAD

**Issue by traetox** [gravwell/wiki#270]
### Remove deprecated *apt-key* command
Update installation process, documentation and/or repository to use best-practice replacement for the soon to be deprecated *apt-key* command currently used.

### Use of signed-by attribute in sources.list.d repo entry recomended (https://wiki.debian.org/DebianRepository/UseThirdParty)
* This is an alternate method supported since atleast apt version 1.1exp15
* Debian 9+ (stretch) supports apt version 1.4.11 (https://packages.debian.org/stretch/apt)
* Support for this feature may be lacking in Debian 8 (jessie) and older.
* Placing the repository key in /usr/share/keyrings/gravwell-archive-keyring.gpg and using the signed-by attribute appears to be a best practice and secure alternative to using *apt-key*
* Have not fully researched impact to Ubuntu or other *nix

### Current Process
```
sudo apt install apt-transport-https gnupg curl
curl https://update.gravwell.io/debian/update.gravwell.io.gpg.key | sudo apt-key add -
echo 'deb [ arch=amd64 ] https://update.gravwell.io/debian/ community main' | sudo tee /etc/apt/sources.list.d/gravwell.list
```

### Recomended Process
```
sudo apt install apt-transport-https
sudo wget -O /usr/share/keyrings/gravwell-archive-keyring.asc https://update.gravwell.io/debian/update.gravwell.io.gpg.key
sudo echo 'deb [ arch=amd64 signed-by=/usr/share/keyrings/gravwell-archive-keyring.asc ] https://update.gravwell.io/debian/ community main' | sudo tee /etc/apt/sources.list.d/gravwell.list
```

Make sure to call out the old method and describe which versions should use the old method.

**Comment by djfritz** [comment]
This is already done in the Quickstart, but needs updating in the beta and CE pages
