### ISSUE TITLE
Searching Documentation

### ISSUE THREAD

**Issue by ashnwade** [gravwell/wiki#413]
When going to the documentation page and searching for: **search array**
the returned results did not include JSON Arrays.

When searching for: **array**
JSON Arrays is the top search result

The first search returned only results that had BOTH search terms. not EITHER term
    • return results with either term and sort by relevancy (both terms first)
      OR
    • offer radio buttons for:
        ◦ includes all words
        ◦ includes any words
        ◦ includes exact phrase
      then return results that are appropriate based on the selected criteria

**Comment by kris-watts-gravwell** [comment]
https://github.com/realTristan/BetterCache might be an option for providing better searching in the wiki
