### ISSUE TITLE
Timestamp extraction caveats with ingesters

### ISSUE THREAD

**Issue by ashnwade** [gravwell/wiki#435]
Timestamp extraction caveats with ingesters. We recently added language on this on the doc server. An overview in the training materials would be useful.

**Comment by ashnwade** [comment]
Also needed in training: https://github.com/gravwell/training/issues/62

**Comment by ashnwade** [comment]
https://docs.gravwell.io/#!ingesters/ingesters.md#Time

**Comment by kris-watts-gravwell** [comment]
this seems well covered here: https://docs.gravwell.io/#!ingesters/ingesters.md#Time

I honestly don't know what else to add.
