### ISSUE TITLE
O365: missing image permission.png

### ISSUE THREAD

**Issue by ashnwade** [gravwell/wiki#515]
### What are the steps to reproduce this issue?
Go to `https://docs.gravwell.io/#!ingesters/o365.md#Basic_Configuration`
Scroll down and you will see that there is a missing image:
![image](https://user-images.githubusercontent.com/107071905/203164055-58b93895-eab0-40a7-8ad9-3d81233a5bf3.png)

### What were you expecting to happen?
All images would load and appear correctly

### Any other comments?
https://github.com/gravwell/wiki/pull/502 is missing permission.png from the list of files

**Comment by kris-watts-gravwell** [comment]
png is there now.
