### ISSUE TITLE
Small Documentation error for The Windows Events Forwarder

### ISSUE THREAD

**Issue by Aztek1337** [gravwell/wiki#566]
# Tiny typo on the Winevents docs

On this page - https://github.com/gravwell/wiki/blob/ab79f56ddc9c2a0591a05565e68c06ad2933e6fa/ingesters/winevent.md#silent-installation on the code block to restart the service, an "S" is missing on "GravwellEvent Service" should be "GravwellEvent<**s**> Service"

The correct cmd would be
....
sc stop "GravwellEvent**s** Service"
sc start "GravwellEvent**s** Service"

**Comment by kris-watts-gravwell** [comment]
Good catch, PR in and merged.

Thank you!
