### ISSUE TITLE
Search bar doesn't show sometimes

### ISSUE THREAD

**Issue by michaelwisely** [gravwell/wiki#59]
Occasionally, when the wiki is loaded, the search bar won't appear. The cause seems to be that `search.js` sometimes can't find the search field element. We handle the "missing element" case [here](https://github.com/gravwell/wiki/commit/32b37b186b766e1fb782f035fa24a4e9ab5eb4da#diff-4be111b67af9a1593260ba8451ad3653) to prevent an error, but we still don't show the search bar.

Since the wiki loads content with JS, my guess is that we're looking for the search bar element before it's been added to the document. Maybe we could throw in a timeout to wait for it to show up?

**Comment by traetox** [comment]
appears good after latest merge
