### ISSUE TITLE
Cloud Archive Docs: provide docs on hosting and point at github

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/wiki#672]
wiki still says to contact sales about cloud archive, its open source now.  Point at the OSS repo.

We also need docs on building/hosting/using the cloud archive server.

Either make docs on the OSS README or add docs to our docs page.

Either way, need docs on hosting the server with some of the setups

**Comment by john-floren-gravwell** [comment]
Are we going to package cloud archive, or just tell people to build it themselves? If we're going to package it, there's no point in writing deployment docs until it's packaged.

**Comment by kris-watts-gravwell** [comment]
at a minimum there should be some light deployment examples on the README of that repo

**Comment by kris-watts-gravwell** [comment]
we should also package it

**Comment by john-floren-gravwell** [comment]
updated the readme, will document more after we package it.

**Comment by ashnwade** [comment]
John packaged this. Just needs wiki docs now.
