### ISSUE TITLE
Flows: top level "common uses" section that has  more examples

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/wiki#691]
## What is the enhancement to be made?

It can be tough getting started with flows.  We need a top level "common uses" section that lays out a few basic use cases with concrete examples.

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)

Make it easier for people to see and potentially google for use case driven flows

## Any other comments?

Things that should be in this top level section:

Run query -> format text -> send email

Run query -> send data to HTTP webhook

Run query -> send formatted mattermost message

Hit Web API ->  format data -> ingest

Generate aggregate data on specific tag and ingest

Generate PDF from several queries and webhook -> upload to slack -> upload to Email

**Comment by john-floren-gravwell** [comment]
https://docs.gravwell.io/flows/patterns/patterns.html would it make sense to expand this page with these examples?
