### ISSUE TITLE
Tools Page - Document the one-off tools that are useful

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/wiki#696]
## What is the enhancement to be made?

Add a "Tools" documentation page that links to and documents the useful one-off tools.

- [x] accountUnlock - unlocking accounts, resetting passwords
- [x] ingestBenchmark - simple blackhole "indexer" useful for estimating data volumes and ingest rates
- [x] fileFollowStateDump - dump the state of file follower
- [x] timegrinderShowme - shows timegrinder activity and info (may be done)
- [x] export - show how to do a bulk export of data

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)

Useful tools, we end up documenting them over and over when asked for

Make a page, link them, show SHA256 and MD5 and publish

## Any other comments?

Not urgent, but totally useful.

**Comment by david-fritz-gravwell** [comment]
Closing remaining tools, referenced in #730, as won't fix.
