### ISSUE TITLE
Document: Tag Access Controls and Tag Globbing

### ISSUE THREAD

**Issue by ashnwade** [gravwell/wiki#734]
## What is the enhancement to be made?
Document tag access controls and tag globbing. 

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)
Tag globbing is new in the GUI with the 5.3.2 release.
We have documentation for CBAC user capabilities grants, but I don't think we have any documentation for tag access controls.

**Comment by kris-watts-gravwell** [comment]
https://github.com/gravwell/wiki/pull/735
