### ISSUE TITLE
All ingester pages should have the download link at the top of the page

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/wiki#747]
Every ingester info page should have the download link at the top so that people do not have to leave the page to get to the download

**Comment by john-floren-gravwell** [comment]
Discussion in chat: do we actually want to emphasize the shell installers that much? It mainly leads to people running out-of-date shit, and most of our customers are on either RHEL or Debian

**Comment by ashnwade** [comment]
related to: #748 - maybe we do this for the Windows ingester pages only?
