### ISSUE TITLE
Migrate: Splunk Index-Sourcetype-To-Tag parsing error

### ISSUE THREAD

**Issue by mike-wade-gravwell** [gravwell/wiki#839]
## Instructions
When using the **Index-Sourcetype-To-Tag** stanza in migrate.conf the instructions say to use  <index>,<sourcetype>:<tag>.

Using a sourcetype with a colon causes migrate_tool to fail on start

migrate.conf
`[Splunk "splunk1"]
    Token=`<token>`
        # Specifies the Splunk server. Make sure port 8089 (REST API) is open.
    Server=192.168.0.1
    Ingest-From-Unix-Time=<unix-time>
    Index-Sourcetype-To-Tag=main:"log:source":logdata

`

Error
`<8>1 2023-11-03T21:22:09.311115Z <host> migrate - migrate/main.go:100 [<host>@1 error="improper index sourcetype to tag mapping \"main:log:source:logdata\", have 1 fields need 3"] Failed to initialize splunk`

## Any other comments?

A workaround is to remove the line entirely.

## What versions of software are you using?

Current version: 5.4.1
Server build: 587f05ed
Client build: 7ba59c2d

**Comment by john-floren-gravwell** [comment]
Basically it needs to be `index,sourcetype,tag` (all comma-separated, no colons involved):

```
Index-Sourcetype-To-Tag=main,"log:source",logdata
```

Note that yes, you can use commas in stuff as long as you quote it:

```
Index-Sourcetype-To-Tag=main,"log,source",logdata
```

I have fixed the wiki
