### ISSUE TITLE
anko search module: documentation is broken up into a separate page, not sure why.

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/wiki#842]
## Who was the customer who requested this feature?

Several

## What is the feature to be added?

The anko search module documentation page is some sort of tiny stub: https://docs.gravwell.io/search/anko/anko.html

The real docs are here: https://docs.gravwell.io/scripting/anko.html

## Why should we add this feature? (Business justification? What problem is the feature trying to solve?)

this is really confusing and doesn't serve any real purpose.

the `scripting/anko.html` page should be in `/anko/anko.html`

## How does this feature address the above problem?

Makes it less confusing

## Any other comments?

we can still link to the full anko docs.

**Comment by ashnwade** [comment]
Should be fixed by https://github.com/gravwell/wiki/pull/836
