### ISSUE TITLE
Windows Quickstart Download Links 404

### ISSUE THREAD

**Issue by mike-wade-gravwell** [gravwell/wiki#859]
## What are the steps to reproduce this issue?

https://docs.gravwell.io/quickstart/downloads.html Both of the windows download links 404

https://update.gravwell.io/archive/5.4.3/installers/gravwell_win_events_5.4.3.msi
https://update.gravwell.io/archive/5.4.3/installers/gravwell_file_follow_5.4.3.msi

Both of these links 404

## What happens?

Both links 404
...

## What were you expecting to happen?

Files to download
...

## Any logs, error output, etc?

...

## Any other comments?

...

## What versions of software are you using?

**Browser:** ...

**GUI Build Version:** ...

**Comment by kris-watts-gravwell** [comment]
you caught us right in the middle of a deployment, not an issue.
