### ISSUE TITLE
Update HTTP HEC ingester docs

### ISSUE THREAD

**Issue by kris-watts-gravwell** [gravwell/wiki#913]
## What is the enhancement to be made?

Document `Token-Name`

Document `Routed-Token-Value`

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)

docs are out of date

## Any other comments?

both are new for 5.4.5

**Comment by ashnwade** [comment]
This should also be updated for the HEC ingester: 
if you get a timestamp with unix time of zero (or some other stupid low number) just use NOW
