### ISSUE TITLE
documentation for anko `newEntry` is wrong

### ISSUE THREAD

**Issue by traetox** [gravwell/wiki#96]
Docs say: `newEntry() entry creates an entirely new entry, with the timestamp set to the current time.`

Function definition is: `func(ts time.Time, data []byte) types.StringTagEntry`

**Comment by floren** [comment]
For good or for ill, we define different newEntry functions for the anko module vs. scheduled searches. The docs you are referring to are for the anko module (https://docs.gravwell.io/#!scripting/anko.md). The function definition you are looking at, however, is the one used for scheduled scripts, as documented at http://localhost:3001/#!scripting/scriptingsearch.md
